---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkz3dtrsnk2pyzow/public_html/rossiuk.xyz/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp guard.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R tools $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
