CREATE TABLE IF NOT EXISTS sms_schedules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  recipient_ciphertext TEXT NOT NULL,
  recipient_last4 CHAR(4) NOT NULL,
  message_ciphertext MEDIUMTEXT NOT NULL,
  message_units SMALLINT UNSIGNED NOT NULL,
  message_type VARCHAR(8) NOT NULL,
  scheduled_at_utc DATETIME NOT NULL,
  scheduled_at_kst DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL,
  provider_group_id VARCHAR(64) NULL,
  provider_message_id VARCHAR(64) NULL,
  provider_status VARCHAR(32) NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  cancelled_at DATETIME NULL,
  completed_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sms_public_id (public_id),
  UNIQUE KEY uq_sms_group_id (provider_group_id),
  KEY idx_sms_status_updated (status, updated_at),
  KEY idx_sms_scheduled (scheduled_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
